### ISSUE TITLE
PR汇总

### ISSUE THREAD

**Issue by zzc98** [zzc98/mmclassification#1]
代码：
- Stanford Cars [https://github.com/open-mmlab/mmclassification/pull/893](https://github.com/open-mmlab/mmclassification/pull/893)
- ArcFace Fead [https://github.com/open-mmlab/mmclassification/pull/934](https://github.com/open-mmlab/mmclassification/pull/934)
- ArcFace Loss [https://github.com/open-mmlab/mmclassification/pull/926](https://github.com/open-mmlab/mmclassification/pull/926)
- Reduction neck [https://github.com/open-mmlab/mmclassification/pull/978](https://github.com/open-mmlab/mmclassification/pull/978)
- Metric mAP@k for image retrieval [https://github.com/open-mmlab/mmclassification/pull/980](https://github.com/open-mmlab/mmclassification/pull/980)
- InShop Dataset (retrieval) [https://github.com/open-mmlab/mmclassification/pull/1019](https://github.com/open-mmlab/mmclassification/pull/1019)
- DOLG Neck [https://github.com/open-mmlab/mmclassification/pull/1053](https://github.com/open-mmlab/mmclassification/pull/1053)
- Retriever [https://github.com/open-mmlab/mmclassification/pull/1055](https://github.com/open-mmlab/mmclassification/pull/1055)
- Google Landmark v2 Retrieval Dataset [https://github.com/open-mmlab/mmclassification/pull/1056](https://github.com/open-mmlab/mmclassification/pull/1056)

实验：
- [Experimental results of image retrieval on Google-Lanmark-V2 dataset](https://github.com/open-mmlab/mmclassification/issues/981)

**Comment by lainxx** [comment]
> 代码：
> 
> * Stanford Cars [[Feature] Support Stanford Cars dataset. open-mmlab/mmclassification#893](https://github.com/open-mmlab/mmclassification/pull/893)
> * ArcFace Fead [Add ArcFace head for image retrieval open-mmlab/mmclassification#934](https://github.com/open-mmlab/mmclassification/pull/934)
> * ArcFace Loss [Add arcface head open-mmlab/mmclassification#926](https://github.com/open-mmlab/mmclassification/pull/926)
> * Reduction neck [[Feature] add reduction for neck open-mmlab/mmclassification#978](https://github.com/open-mmlab/mmclassification/pull/978)
> * Metric mAP@k for image retrieval [update metric mAP@k for image retrieval open-mmlab/mmclassification#980](https://github.com/open-mmlab/mmclassification/pull/980)
> * InShop Dataset (retrieval) [[Feature] Support InShop Dataset (Image Retrieval). open-mmlab/mmclassification#1019](https://github.com/open-mmlab/mmclassification/pull/1019)
> * DOLG Neck [[Feature] Add DOLG neck for image retrieval open-mmlab/mmclassification#1053](https://github.com/open-mmlab/mmclassification/pull/1053)
> * Retriever [[Feature] Add Base Retriever and Image2Image Retriever for retrieval tasks open-mmlab/mmclassification#1055](https://github.com/open-mmlab/mmclassification/pull/1055)
> * Google Landmark v2 Retrieval Dataset [[Feature] Add Google Landmark v2 retrieval dataset open-mmlab/mmclassification#1056](https://github.com/open-mmlab/mmclassification/pull/1056)
> 
> 实验：
> 
> * [Experimental results of image retrieval on Google-Lanmark-V2 dataset](https://github.com/open-mmlab/mmclassification/issues/981)



> 代码：
> 
> * Stanford Cars [[Feature] Support Stanford Cars dataset. open-mmlab/mmclassification#893](https://github.com/open-mmlab/mmclassification/pull/893)
> * ArcFace Fead [Add ArcFace head for image retrieval open-mmlab/mmclassification#934](https://github.com/open-mmlab/mmclassification/pull/934)
> * ArcFace Loss [Add arcface head open-mmlab/mmclassification#926](https://github.com/open-mmlab/mmclassification/pull/926)
> * Reduction neck [[Feature] add reduction for neck open-mmlab/mmclassification#978](https://github.com/open-mmlab/mmclassification/pull/978)
> * Metric mAP@k for image retrieval [update metric mAP@k for image retrieval open-mmlab/mmclassification#980](https://github.com/open-mmlab/mmclassification/pull/980)
> * InShop Dataset (retrieval) [[Feature] Support InShop Dataset (Image Retrieval). open-mmlab/mmclassification#1019](https://github.com/open-mmlab/mmclassification/pull/1019)
> * DOLG Neck [[Feature] Add DOLG neck for image retrieval open-mmlab/mmclassification#1053](https://github.com/open-mmlab/mmclassification/pull/1053)
> * Retriever [[Feature] Add Base Retriever and Image2Image Retriever for retrieval tasks open-mmlab/mmclassification#1055](https://github.com/open-mmlab/mmclassification/pull/1055)
> * Google Landmark v2 Retrieval Dataset [[Feature] Add Google Landmark v2 retrieval dataset open-mmlab/mmclassification#1056](https://github.com/open-mmlab/mmclassification/pull/1056)
> 
> 实验：
> 
> * [Experimental results of image retrieval on Google-Lanmark-V2 dataset](https://github.com/open-mmlab/mmclassification/issues/981)

Thank you very much for your sharing. Is it convenient to share the relevant training configuration?
